### Continuous Bandit


In [1]:
import numpy as np

In [14]:
n = 10
C = np.random.randn(n, n)
C = np.matmul(C.T, C)
a = np.ones(shape=(n, )) * 4

def reward(act):
    x = act - a
    return - np.matmul(np.matmul(x.T, C), x)

In [17]:
act = np.random.randn(n)

reward(act)

-3004.800958326176

In [ ]:
def gp_policy_gradient(act, theta, y):
    pass

def qfun(w):
    pass

In [18]:
it = 0

theta = np.zeros(n)
y = np.zeros(n)


while it < 10:
    act = np.random.normal(theta, np.exp(y))
    r = reward(act)
    
    
    it += 1

In [19]:
np.random.normal(theta, np.exp(y))

array([-1.07352094,  0.60489519,  0.71227002, -1.43290183,  1.05760992,
       -0.85462916,  1.21373511, -1.76420995, -0.69480067,  1.01061215])

In [20]:
theta

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.exp(y)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])