In [1]:
import numpy as np

In [53]:
n = 10
m = 10
A = np.random.randn(n, m)
A += np.diag(np.sign(np.diag(A)) * 5)
b = np.random.randn(n)

print A
x0 = np.linalg.solve(A, b)
x0

[[ 5.12700658 -0.21858254  0.48355156  1.56668432  0.34489236 -1.93740772
  -0.87610686  0.54476428 -0.02069386 -1.15826282]
 [ 0.84930938  5.7650278  -1.40007769 -0.57596706 -1.34037743 -0.19333354
   2.07059873  0.93946145 -0.84460457  0.76988204]
 [-0.53837378 -0.03999283  5.8296918   0.10784172  0.25708836 -0.64817818
  -0.85078273 -0.19905932 -1.86768937 -0.70165895]
 [ 2.13403868  0.12902118  0.4546132   5.14876658  1.87217934  0.76729727
  -1.32168735 -1.0620557   0.07549819 -0.75512625]
 [-1.18500297 -0.4890768  -0.02283978 -0.16313348  5.18765254 -0.2341487
  -0.46868923  0.15796974  0.76536691 -1.43969644]
 [ 0.73134077 -0.66764963  1.36034371 -0.50851661  0.06331636 -6.45725135
  -0.41279427 -1.51073972 -2.03810668 -0.44060871]
 [ 0.43004739  1.14879691  0.33129874 -0.6450202   0.15713503 -0.56307464
  -8.03120056 -1.37044279  2.74743023 -0.53760086]
 [-0.09331048 -0.27367178  0.29933229 -0.91693435 -0.09397183 -1.66615908
  -0.47727973 -5.56125997 -0.7860968  -0.53815174]
 

array([-0.21315434, -0.02981617,  0.03274141,  0.32403459,  0.04962351,
        0.11703491, -0.18985401,  0.161088  , -0.01891043,  0.09288528])

In [54]:
D = np.diag(A) 
B = A - np.diag(D)
DB = np.matmul(np.diag(1.0/D), B)
B

array([[ 0.        , -0.21858254,  0.48355156,  1.56668432,  0.34489236,
        -1.93740772, -0.87610686,  0.54476428, -0.02069386, -1.15826282],
       [ 0.84930938,  0.        , -1.40007769, -0.57596706, -1.34037743,
        -0.19333354,  2.07059873,  0.93946145, -0.84460457,  0.76988204],
       [-0.53837378, -0.03999283,  0.        ,  0.10784172,  0.25708836,
        -0.64817818, -0.85078273, -0.19905932, -1.86768937, -0.70165895],
       [ 2.13403868,  0.12902118,  0.4546132 ,  0.        ,  1.87217934,
         0.76729727, -1.32168735, -1.0620557 ,  0.07549819, -0.75512625],
       [-1.18500297, -0.4890768 , -0.02283978, -0.16313348,  0.        ,
        -0.2341487 , -0.46868923,  0.15796974,  0.76536691, -1.43969644],
       [ 0.73134077, -0.66764963,  1.36034371, -0.50851661,  0.06331636,
         0.        , -0.41279427, -1.51073972, -2.03810668, -0.44060871],
       [ 0.43004739,  1.14879691,  0.33129874, -0.6450202 ,  0.15713503,
        -0.56307464,  0.        , -1.37044279

In [55]:
x = np.random.rand(m)

for it in range(10):
    x = - np.matmul(DB, x) + 1.0/D * b
    print 'iter', it, 'error', np.linalg.norm(x - x0)
print x

iter 0 error 0.957122549324
iter 1 error 0.464202165856
iter 2 error 0.220551850638
iter 3 error 0.170690210316
iter 4 error 0.0890033798173
iter 5 error 0.0230059953945
iter 6 error 0.0123778986143
iter 7 error 0.00711473144629
iter 8 error 0.00401585478008
iter 9 error 0.00267363592995
[-0.21450436 -0.02992594  0.03220058  0.32309706  0.05001102  0.11790343
 -0.18993429  0.16148156 -0.01886887  0.09463876]


In [22]:
x

array([ -952228.25523232, -1689077.11075653, -1725453.29709574,
       -1774238.74597523,    89899.0286491 ,  2680124.21399711,
        -787941.90293928,  1373646.67401951,  -782377.07062719,
         357819.44908366])